####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, MAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  MAZ: 1
  TAZ: 310

  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households_GQ.csv
    index_col: hh_id
  - tablename: persons
    filename : seed_persons_GQ.csv
    column_map:
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
  - tablename: geo_cross_walk
    filename : geo_crosswalksGQ.csv
  - tablename: MAZ_control_data
    filename : control_totals_maz.csv
  - tablename: TAZ_control_data
    filename : control_totals_taz.csv
  - tablename: REGION_control_data
    filename : control_totals_region.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: GQWGTP
household_id_col: hh_id
total_hh_control: num_gq


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_MAZ
    - summary_TAZ
    - summary_MAZ_PUMA
    - summary_TAZ_PUMA
    - expanded_household_ids
    - summary_REGION
    - summary_hh_weights
    - summary_MAZ_aggregate
    - summary_TAZ_aggregate


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - NP
      - hh_id
  persons:
    filename: synthetic_persons.csv
    columns:
      - per_num
      - AGEP
      - hh_id


# Steps for base mode
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    #- sub_balancing.geography=TAZ
    - sub_balancing.geography=MAZ
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
